### ISSUE TITLE
add_debug_modbus

### ISSUE THREAD

**Issue by MageTomcat14** [Panduza/panduza-adapters-sdk#7]
Bonjour,

J'ouvre cette issue concernant l'utilisation du debug sur l'uart car je souhaite savoir comment les données modbus sont envoyés et reçu sur la PICO à cause d'une erreur que je dois modifier.

J'utilise l'uart1 et les ports GP4 et GP5 de la PICO qui sont relié à un ftdi 3v3. Toutefois, je constate que ce moyen de debug sans passer par l'usb parasite totalement les données MODBUS envoyés par le port USB. Pensez-vous savoir comment régler ce problème. J'utilise l'uart de debug dans les fonctions pza_platform_modbus_read et pza_platform_modbus_write dans le fichier modbus.c

Pour cette issue, je travaille sur la branche 7-add_debug_modbus

Merci.

**Comment by BCadet** [comment]
Bonjour, 
peux-tu poster du code concernant ton problème ? la branche 7-add_debug_modbus n'existe pas...

**Comment by MageTomcat14** [comment]
Bonjour,
La branche a été créée, la configuration et print de debug se trouvent dans le modbus.c

**Comment by MageTomcat14** [comment]
Bonjour,

Le bug est résolu, cela ne venait pas du firmware. Je close l'issue.
