### ISSUE TITLE
 pza-pico-modbus-dio => make the built-in led on when pi gets power

### ISSUE THREAD

**Issue by XdoctorwhoZ** [Panduza/panduza-adapters-sdk#8]
I would be nice to see that the board is alive by settings the built-in led on when the program is running

**OR make the led on at startup then blink when data arrives**

**Comment by BCadet** [comment]
Hi, in order to be cross-platform, I think it is not a good idea to dedicate a specific pin to a "status led". The led on the raspberry pi pico is maped to a gpio accessible by the modbus (coil 24 I guess) so in the current impelmentation it is up to the user to implement a blink on this pin.

**Comment by XdoctorwhoZ** [comment]
Ok now I see why we did it like this. This issues is not useful anymore
